---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream8

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: amazon.aws
        version: "<4.0.0"
      - name: community.aws
        version: "<3.0.0"
      - name: community.general
  python:
    - awscli
    - dnspython
    - credstash
  python_interpreter:
    package_system: "python38"
    python_path: "/usr/bin/python3"

#additional_build_steps:
#  prepend_base:
#    - RUN $PKGMGR install -y python3
#options:
#  package_manager_path: /usr/bin/yum
