---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream8

dependencies:
  ansible_core:
    package_pip: ansible-core ansible-lint
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: amazon.aws
        version: "<4.0.0"
      - name: community.aws
        version: "<3.0.0"
      - name: community.general
  python_interpreter:
    package_system: "python38"
